[package]
name = "nu_plugin_template"
version = "0.1.0"
edition = "2021"
description = "Templating in Nushell, powered by TinyTemplate"

[dependencies]
nu-plugin = { workspace = true }
nu-protocol = { workspace = true }
serde_json = "1.0.127"
tinytemplate = "1.2.1"
